<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE xml [
	<!ELEMENT xml (personal_accounts)>
	<!ATTLIST xml xmlns CDATA #REQUIRED>
	<!ELEMENT personal_accounts (personal_account*)>
	<!ELEMENT personal_account (owner, name, wall, video_album?, photo_album?)>
	<!ATTLIST personal_account id CDATA #REQUIRED>
	<!ELEMENT owner (#PCDATA)>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT wall (#PCDATA)>
	<!ELEMENT video_album (#PCDATA)>
	<!ELEMENT photo_album (#PCDATA)>
]>

<xml xmlns="http://www.example.org/NewXMLSchema">
	<personal_accounts>
	
		<personal_account id="1">
			<owner>John</owner>
			<name>John_Account</name>
			<wall>Wall1</wall>
			<video_album>VideoAlbum1</video_album>
			<photo_album>PhotoAlbum1</photo_album>
		</personal_account>
		
		<personal_account id="2">
			<owner>Jack</owner>
			<name>Jack_Account</name>
			<wall>Wall2</wall>
			<video_album>VideoAlbum2</video_album>
			<photo_album>PhotoAlbum2</photo_album>
		</personal_account>
		
		<personal_account id="3">
			<owner>Bob</owner>
			<name>Bob_Account</name>
			<wall>Wall3</wall>
			<video_album>VideoAlbum3</video_album>
			<photo_album>PhotoAlbum3</photo_album>
		</personal_account>
		
	</personal_accounts>
</xml>