=== dzmitrygrib/automation_lab/Dealer/src/qom/dealer/data/xsdfiles/ClientSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="xml">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Human">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="client" id="C1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C2">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C3">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C4">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C5">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C6">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C8">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="client" id="C9">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="first_name" type="xs:string" />
										<xs:element name="wish" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dzmitrygrib/automation_lab/Dealer/src/qom/dealer/data/xmlfiles/Clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<xml 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsdfiles//ClientSchema.xsd">
	<human>
		<client id="C1">
			<first_name>Jack</first_name>
			<wish>Audi</wish>
		</client>
		<client id="C2">
			<first_name>Tom</first_name>
			<wish>Minsk</wish>
		</client>
		<client id="C3">
			<first_name>Peter</first_name>
			<wish>Bmw</wish>
		</client>
		<client id="C4">
			<first_name>Harry</first_name>
			<wish>Kia</wish>
		</client>
		<client id="C5">
			<first_name>Maria</first_name>
			<wish>Harley</wish>
		</client>
		<client id="C6">
			<first_name>Dima</first_name>
			<wish>Iveco</wish>
		</client>
		<client id="C7">
			<first_name>Nick</first_name>
			<wish>Scania</wish>
		</client>
		<client id="C8">
			<first_name>Jerry</first_name>
			<wish>Maz</wish>
		</client>
		<client id="C9">
			<first_name>Ron</first_name>
			<wish>Minsk</wish>
		</client>
	</human>
</xml>
