=== dzmitrygrib/automation_lab/Dealer/src/qom/dealer/data/xsdfiles/TruckSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">

	<xs:element name="price" type="sx:string" />
	<xs:element name="capacity" type="xs:string" />

	<xs:atribute name="brand" type="xs:string" />

	<xs:element name="maz" seialId="11" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="maz" seialId="12" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="iveco" seialId="21" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="iveco" seialId="22" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="scania" seialId="31" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="scania" seialId="32" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="price" />
				<xs:element ref="capacity" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="truck" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="maz" serialId="11" />
				<xs:element name="maz" seialId="12" />
				<xs:element name="iveco" seialId="21" />
				<xs:element name="iveco" seialId="22" />
				<xs:element name="scania" seialId="31" />
				<xs:element name="scania" seialId="32" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="car" type="xs:string">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="truck" />
			</xs:sequence>
			<xs:atribute name="brand" use="required" />
		</xs:complexType>
	</xs:element>

</schema>

=== dzmitrygrib/automation_lab/Dealer/src/qom/dealer/data/xmlfiles/Truck.xml
<?xml version="1.0" encoding="UTF-8"?>
<car brand="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="xsdfiles//TruckSchema.xsd">
	<truck>
		<maz serialId="11">
			<price>5000</price>
			<capacity>100</capacity>
		</maz>
		<maz serialId="12">
			<price>6000</price>
			<capacity>110</capacity>
		</maz>
		<iveco serialId="21">
			<price>6000</price>
			<capacity>110</capacity>
		</iveco>
		<iveco serialId="22">
			<price>6200</price>
			<capacity>85</capacity>
		</iveco>
		<scania serialId="31">
			<price>6500</price>
			<capacity>90</capacity>
		</scania>
		<scania serialId="32">
			<price>6900</price>
			<capacity>100</capacity>
		</scania>
	</truck>
</car>
