=== dzmitrygrib/automation_lab/src/data/CataclismInformationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- problems -->
<!-- <xs:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/CataclismInformationSchema" 
	xmlns:tns="http://www.example.org/CataclismInformationSchema" elementFormDefault="qualified"> -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Cataclisms">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="hurricane" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
					<xs:simpleContent>
					<xs:extension base="xs:string">
					<xs:attribute type="xs:string" name="name" use="optional"></xs:attribute>
					<xs:attribute type="xs:string" name= "year" use="optional"></xs:attribute>
					</xs:extension>
					</xs:simpleContent>
					</xs:complexType>	

				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dzmitrygrib/automation_lab/src/data/CataclismInformation.xml
<?xml version="1.0" encoding="UTF-8"?>
<Cataclisms xmlns:xsi="http://www.w3.org/2001/XMLSchema"
xsi:noNamespaceSchemaLocation="CataclismInformationSchema.xsd">
	<hurricane name="Rita" year="2005">Information</hurricane>
	<hurricane name="Wilma" year="2006">Information</hurricane>
	<hurricane name="Ivan" year="2004">Information</hurricane>
	<hurricane name="Ike" year="2004">Information</hurricane>
	<hurricane name="Andrew" year="2006">Information</hurricane>
	<hurricane name="Irma" year="2004">Information</hurricane>
	<hurricane name="Sandy" year="2005">Information</hurricane>
	<hurricane name="Maria" year="2006">Information</hurricane>
	<hurricane name="Harvey" year="2004">Information</hurricane>
	<hurricane name="Katrina" year="2005">Information</hurricane>
</Cataclisms>
